var tu = [{"id":1,"name":"What is Technology","description":"Explains about what is Technology.","alias":"","published":1,"subjectname":"","subjectid":53,"content":"<p>Technology (from <a href=\"http:\/\/en.wikipedia.org\/wiki\/Ancient_Greek\" title=\"Ancient Greek\">Greek<\/a> &tau;\u03ad&chi;&nu;&eta;, techne, &quot;art, skill, cunning of hand&quot;; and -&lambda;&omicron;&gamma;\u03af&alpha;, <a href=\"http:\/\/en.wiktionary.org\/wiki\/-logia\" title=\"wikt:-logia\">-logia<\/a><a href=\"http:\/\/en.wikipedia.org\/wiki\/Technology#cite_note-Liddell_1980-1\">[1]<\/a>) is the making, modification, usage, and knowledge of <a href=\"http:\/\/en.wikipedia.org\/wiki\/Tool\" title=\"Tool\">tools<\/a>, <a href=\"http:\/\/en.wikipedia.org\/wiki\/Machine\" title=\"Machine\">machines<\/a>, techniques, <a href=\"http:\/\/en.wikipedia.org\/wiki\/Craft\" title=\"Craft\">crafts<\/a>, <a href=\"http:\/\/en.wikipedia.org\/wiki\/System\" title=\"System\">systems<\/a>, and methods of organization, in order to solve a problem, improve a pre-existing solution to a problem, achieve a goal, handle an applied input\/output relation or perform a specific function. It can also refer to the collection of such tools, including machinery, modifications, arrangements and procedures. Technologies significantly affect human as well as other animal species&#39; ability to control and adapt to their natural environments. The term can either be applied generally or to specific areas: examples include construction technology, medical technology, and information technology.<\/p>\r\n","createdby":1,"exams":"a:1:{s:4:\"true\";b:0;}","created_at":"2013-10-13 07:25:49","updated_at":"2013-10-17 12:01:22","deleted_at":null},{"id":2,"name":"History of Technology","description":"Perfect Article about History of Technology","alias":"","published":1,"subjectname":"","subjectid":53,"content":"<p>See Presentation<\/p>\r\n","createdby":1,"exams":"a:1:{s:4:\"true\";b:0;}","created_at":"2013-10-13 07:57:52","updated_at":"2013-10-13 10:53:12","deleted_at":null},{"id":3,"name":"Testsdfs","description":"wafesfewifh","alias":"","published":1,"subjectname":"","subjectid":48,"content":"<p>sf nsekhfesjkhfs ef hash af wehfeks lshf fshdkfhsfvhlsdra<\/p>\r\n","createdby":1,"exams":null,"created_at":"2013-10-17 06:48:21","updated_at":"2013-10-17 07:00:02","deleted_at":null}];

	$.each(tu,function(i){
		var data = '<li><a href="#tutorial'+this.id+'"  data-transition="slidedown">'+this.name+'</a></li>';
		var content = '<div data-role="page" id="tutorial'+this.id+'"><div data-role="header"><h3>'+this.name+'</h3></div><div data-role="content">'+this.content+'</div><a href="#tutorials" data-role="button" data-theme="d" data-inline="true" data-mini="true" data-icon="back" data-transition="flow">Back</a></div>';
		$(data).appendTo('#tutorial_list').trigger('refresh');
		// $('#tutorial_list').listview('refresh');
		$(content).appendTo('#body').trigger('refresh');
	});
		// $('[data-role=listview]').listview('refresh');

var exam = [{"id":1,"title":"Sample Exam","subjectid":55,"createdby":1,"totalquestions":5,"created_at":"2013-10-18 14:52:28","updated_at":"2013-10-18 15:04:47","deleted_at":null}];
$.each(exam,function(i){
	var data = '<li><a href="#exam'+this.id+'"  data-transition="slidedown">'+this.title+'</a></li>';
	$(data).appendTo('#exam_list').trigger('refresh');
});