

$("#test").click(function(){
	var script = $.parseJSON('{"questiondata":{"questions":{"1":"jkndfvkjndsvknjdsvkjn","2":"njknjnkjnkj","3":"jknjknjknkjnjnk","4":"gvghvghvgvghvghvghvhg","5":"yfytftyfrfdrdfrbfftyftu"},"question":{"1":{"checkboxdata":{"1":"jnkjnknjnknkj","2":"knjnkjnjkn","3":"jnjnkjnkjn","4":"njknkjnkj"},"answers":["2","0","0"]},"2":{"checkboxdata":{"1":"jnjknjknkjnjknjk","2":"jnjknkjnkjnknk","3":"kjnjknjknjknjknjk","4":"jknkjnjknkjnkjnk"},"answers":["2","4","0","0"]},"3":{"checkboxdata":{"1":"jnkjnjknjnhvghv","2":"gvhgvghvhgvhgv","3":"ghvghvghvghvgh","4":"hgvghvhgvhgvgh"},"answers":["2","0","0"]},"4":{"checkboxdata":{"1":"gvhgvhgvhgvghvghvghvh","2":"vghvhgvghvghvhgvhgv","3":"rdtrdtrdtdftrd","4":"frtftrdrt yfbyf"},"answers":["2","3","0","0"]},"5":{"checkboxdata":{"1":"fytfytdrydrydryuf","2":"tydfytfbtdruybdty","3":"ytfbftrdtrnftfbyfty","4":"fgdxewmdgewi"},"answers":["1","3","0","0"]}}}}');	
	$.each(script.questiondata.questions,function(i,tesd){
		// alert(this);
		// alert(i);
	});
	var tu = [{"id":1,"name":"What is Technology","description":"Explains about what is Technology.","alias":"","published":1,"subjectname":"","subjectid":53,"content":"<p>Technology (from <a href=\"http:\/\/en.wikipedia.org\/wiki\/Ancient_Greek\" title=\"Ancient Greek\">Greek<\/a> &tau;\u03ad&chi;&nu;&eta;, techne, &quot;art, skill, cunning of hand&quot;; and -&lambda;&omicron;&gamma;\u03af&alpha;, <a href=\"http:\/\/en.wiktionary.org\/wiki\/-logia\" title=\"wikt:-logia\">-logia<\/a><a href=\"http:\/\/en.wikipedia.org\/wiki\/Technology#cite_note-Liddell_1980-1\">[1]<\/a>) is the making, modification, usage, and knowledge of <a href=\"http:\/\/en.wikipedia.org\/wiki\/Tool\" title=\"Tool\">tools<\/a>, <a href=\"http:\/\/en.wikipedia.org\/wiki\/Machine\" title=\"Machine\">machines<\/a>, techniques, <a href=\"http:\/\/en.wikipedia.org\/wiki\/Craft\" title=\"Craft\">crafts<\/a>, <a href=\"http:\/\/en.wikipedia.org\/wiki\/System\" title=\"System\">systems<\/a>, and methods of organization, in order to solve a problem, improve a pre-existing solution to a problem, achieve a goal, handle an applied input\/output relation or perform a specific function. It can also refer to the collection of such tools, including machinery, modifications, arrangements and procedures. Technologies significantly affect human as well as other animal species&#39; ability to control and adapt to their natural environments. The term can either be applied generally or to specific areas: examples include construction technology, medical technology, and information technology.<\/p>\r\n","createdby":1,"exams":"a:1:{s:4:\"true\";b:0;}","created_at":"2013-10-13 07:25:49","updated_at":"2013-10-17 12:01:22","deleted_at":null},{"id":2,"name":"History of Technology","description":"Perfect Article about History of Technology","alias":"","published":1,"subjectname":"","subjectid":53,"content":"<p>See Presentation<\/p>\r\n","createdby":1,"exams":"a:1:{s:4:\"true\";b:0;}","created_at":"2013-10-13 07:57:52","updated_at":"2013-10-13 10:53:12","deleted_at":null},{"id":3,"name":"Testsdfs","description":"wafesfewifh","alias":"","published":1,"subjectname":"","subjectid":48,"content":"<p>sf nsekhfesjkhfs ef hash af wehfeks lshf fshdkfhsfvhlsdra<\/p>\r\n","createdby":1,"exams":null,"created_at":"2013-10-17 06:48:21","updated_at":"2013-10-17 07:00:02","deleted_at":null}];

	$.each(tu,function(i){
		alert(i);
		alert(this.id);
	});
});
